name: land_registration
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.4.1
  flutter_web3: ^2.1.9
  http: ^0.13.5
  provider: ^6.0.3
  flutter_styled_toast: ^2.1.3
  hovering: ^1.0.4
  flutter_spinkit: ^5.1.0
  flutter_smart_dialog: ^4.5.4+2
  file_picker: ^5.0.1
  url_launcher: ^6.1.5
  flutter_svg: ^1.1.3
  universal_html: ^2.0.8
  pdf: ^3.8.2
  camera: ^0.10.0+1
  camera_web: ^0.3.0
  mapbox_gl: ^0.16.0
  mapbox_search: ^3.0.1+2
  url_strategy: ^0.2.0
  animated_text_kit: ^4.2.2

  image: ^3.0.1
cupertino_icons: ^1.0.2

dev_dependencies:
flutter:
  uses-material-design: true

  assets:
     - src/contracts/Land.json
     - assets/
